### ISSUE TITLE
Line number in debug exceptions

### ISSUE THREAD

**Issue by ShinyStar** [ClockworkDev/ClockworkVSCodePlugin#1]
It'd be nice for the debugger to show the line number in which exceptions occur so it's easier to find the error.

**Comment by arcadiogarcia** [comment]
Added in https://github.com/ClockworkDev/ClockworkCore/commit/b7b8488e1bb892d1590970bf97b22db32a3d04ed

It may fail on platforms other than Edge/W10 since it relies in parsing the stack provided by the exception, available as a (seemingly not standard) string. It shouldn't be an issue until the Runtime is provided to other platforms anyway.
